### PR TITLE
Fix Bandit.HTTP1.Adapter.inform/3 return value

### PR DESCRIPTION
**Pull request by wojtekmach**
Per https://hexdocs.pm/plug/Plug.Conn.Adapter.html#c:inform/3, the callback should return:

    :ok | {:error, :not_supported}

The way Plug.Conn.inform! is implemented at the moment, https://github.com/elixir-plug/plug/blob/v1.15.2/lib/plug/conn.ex#L1335, it looked like Bandit did _not_ implement inform but it sure does!

### CODE REVIEW

**Comment by mtrudel** [comment]
Looks good! I'm going to add a small note to the bandit telemetry docs now that we're losing tracking of inform responses but otherwise lgtm!

**Comment by wojtekmach** [comment]
would it help if the adapter allowed you to send `{:ok, payload}` or whatever makes the most sense? (I believe payload is a name used for arbitrary data, at least in adapter.send_resp/4)

If so that would be a compatible change in Plug and I can help pursuing it.

**Comment by mtrudel** [comment]
(Sorry for terse response, mobile). Ideally, yeah. Plug's chunk api also expects a bare ok (no tuple) and it was the cause of a recent oddball bug as well. Ideally everything in adapter would return the same ok tuple shape

**Comment by wojtekmach** [comment]
We need to wait for https://github.com/elixir-plug/plug/pull/1193 in case there's any change in the contract but this is ready. And when there's a new Plug version I'll send a PR that uses the stricter inform!, https://github.com/mtrudel/bandit/pull/268/commits/18e12ed5eaf1e286b0ef5ab561bc8b847a89a17b#diff-6a1dfdf6de8e0ba81a6ae4eef3f45cf79b7d4a55d7130e228463f9f77a0344e3R1339.

**Comment by mtrudel** [comment]
New plug version is here!

**Comment by mtrudel** [comment]
Merged this since it's erroring out on a couple of other PRs without this

**Pull request merged**
