### PR TITLE
Raise error on send errors for HTTP/1 responses

### LINKED ISSUE #344: Plug.Conn is not closed when user closes the browser's tab (SSE)
Hi,
I have implemented SSE (Server-Sent-Events) using Plug and Bandit, and they work really cool until a user closes browser's tab. For some reason, my Plug.Conn isn't notified/invalidated and I can still send data (although it doesn't appear in Wireshark).  The code looks more or less like this

```elixir
 get "/api/resource/:resource_id/sse/event-stream" do
    viewers = PeerConnection.get_all_running() |> length()

    {:ok, conn} =
      conn
      |> put_resp_header("content-type", "text/event-stream")
      |> put_resp_header("cache-control", "no-cache")
      |> send_chunked(200)
      |> chunk("data: {\"viewerscount\": #{viewers}}\n\n")

    update_viewers_count(conn, self())
  end


  defp update_viewers_count(conn, pid) do
    viewers = PeerConnection.get_all_running() |> length()
    Process.send_after(self(), :update_viewerscount, @viewers_count_update_interval)

    receive do
      :update_viewerscount ->
        {:ok, conn} = chunk(conn, "data: {\"viewerscount\": #{viewers}}\n\n")
        update_viewers_count(conn, pid)
    end
  end
```

When I switched to the cowboy, everything works as expected, i.e. once the tab is closed, a process handling a connection on the server side is also closed.

### PR DESCRIPTION
**Pull request by mtrudel**
The Plug spec doesn't really provide for the effective surfacing of errors from send calls, mostly because Cowboy will (usually) have killed off the connection handler process when the client closes the connection. In Bandit's case, we don't actively kill off connection processes in this situation, so we need to be able to surface these cases effectively. Raising a `Bandit.HTTPError` will bubble through the caller all the way up to Bandit's handler pipeline, and log the error as configured. This is as good of a pattern as we're going to have, and mirrors what we do for reads against closed clients already (tests were added for that case here as well, since they were absent before). 

Fixes #344

### CODE REVIEW

**Comment by CharlesOkwuagwu** [comment]
>>>In Bandit's case, we don't actively kill off connection processes in this situation, so we need to be able to surface these cases

Please is there a reason why you keep the connection process alive when the client closes?

Can this behavior be a configurable option? 

For cases where you need well behaved ServerSentEvents (SSE) killing the process is the correct behavior when the client closes.

**Comment by mtrudel** [comment]
> Please is there a reason why you keep the connection process alive when the client closes?

It's a side-effect of the process model we use; we don't really have a choice. The key thing is that Bandit only uses a single process per connection, and this connection uses the `active: :once` mode of the underlying socket (gen_tcp/ssl). The *only* way to be informed of the underlying connection being closed is to either 1. Receive `:tcp_closed` messages, or  2. handle `{:error, :closed}` tuples that come back from the various socket functions. This PR actively adds support for that second option on send calls.

**Comment by CharlesOkwuagwu** [comment]
I've used the latest version of Bandit, I setup a test specifically for SSE. 

THE handling process stays alive, long after the client closes. 

Us this the expected behavior, for the option 2 you mentioned above?

**Comment by mtrudel** [comment]
> I've used the latest version of Bandit, I setup a test specifically for SSE.

I'd love to see a repro for this! The SSE process is obviously doing *something* while it's sitting idle and it may be possible to have it look at the connection status while it's doing this

**Comment by mtrudel** [comment]
(Feel free to reopen this issue, btw)

**Comment by CharlesOkwuagwu** [comment]
> > I've used the latest version of Bandit, I setup a test specifically for SSE.
> 
> I'd love to see a repro for this! The SSE process is obviously doing _something_ while it's sitting idle and it may be possible to have it look at the connection status while it's doing this

Sorry for the delay

https://github.com/CharlesOkwuagwu/sse_demo

**Comment by CharlesOkwuagwu** [comment]
Please open here in your web browser (MS-edge) https://localhost:9090/demo

**Comment by mtrudel** [comment]
I see the same behaviour in both Chrome & Safari. Unable to test on Edge, but everything here looks like the server is doing the right thing; I wonder if it's an OS issue (I'm on macOS) or a browser issue? Clients don't always close the underlying connection right away after you close the window, instead keeping it open on a timer for possible reuse. I wonder if that could be what's happening in your case?

**Comment by CharlesOkwuagwu** [comment]
> I see the same behaviour in both Chrome & Safari. Unable to test on Edge, but everything here looks like the server is doing the right thing; I wonder if it's an OS issue (I'm on macOS) or a browser issue? Clients don't always close the underlying connection right away after you close the window, instead keeping it open on a timer for possible reuse. I wonder if that could be what's happening in your case?

WOW you are right, I Was closing only the tab. When I close the browser. the process exits.

Sorry for the disturbance.

**Comment by mtrudel** [comment]
No worries! Glad it all got figured out!

**Pull request merged**
