### PR TITLE
Add dark mode logo version in README

### PR DESCRIPTION
**Pull request by nelsonmestevao**
Learn more about this GitHub feature [here](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/).

### CODE REVIEW

**Comment by mtrudel** [comment]
Hrm. This is showing up with broken images in my (light mode) Safari: 

image

**Comment by nelsonmestevao** [comment]
That it's because I am pointing to images that would be in the main of this repository, and the image with light text is not there yet.

But it will work like the [Elixir repo does](https://github.com/elixir-lang/elixir). Example in darkmode (the dark text does not show):

image

**Comment by mtrudel** [comment]
Ah, yes that makes sense!

**Comment by nelsonmestevao** [comment]
I am sorry, I will try to figure out what's wrong :pray:

**Comment by ryanwinchester** [comment]
So much better, thanks

**Pull request merged**
